In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [50]:
# loading the data
df = pd.read_csv('cybersecurity_attacks.csv')

In [51]:
df.head() #getting the top 5 head elements

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Action Taken,Severity Level,User Information,Device Information,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Logged,Low,Reyansh Dugal,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Blocked,Low,Sumer Rana,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Ignored,Low,Himmat Karpe,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Segment C,"Bokaro, Rajasthan",114.133.48.179,Log Data,Alert Data,Firewall
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Blocked,Medium,Fateh Kibe,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...,Segment B,"Jaunpur, Rajasthan",NaN,NaN,Alert Data,Firewall
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Blocked,Low,Dhanush Chad,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Segment C,"Anantapur, Tripura",149.6.110.119,NaN,Alert Data,Firewall

In [52]:
df.tail()   ##accessing the lower bottom 5 elements

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Action Taken,Severity Level,User Information,Device Information,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source
39995,2023-05-26 14:08:42,26.36.109.26,121.100.75.240,31005,6764,UDP,1428,Control,HTTP,Quibusdam ullam consequatur consequuntur accus...,...,Logged,Medium,Adira Madan,Mozilla/5.0 (iPad; CPU iPad OS 14_2_1 like Mac...,Segment A,"Nashik, Manipur",NaN,Log Data,Alert Data,Firewall
39996,2023-03-27 00:38:27,17.21.163.81,196.108.134.78,2553,28091,UDP,1184,Control,HTTP,Quaerat neque esse. Animi expedita natus commo...,...,Logged,High,Rati Dara,Mozilla/5.0 (Windows; U; Windows 98; Win 9x 4....,Segment C,"Vadodara, Mizoram",60.51.30.46,Log Data,NaN,Firewall
39997,2022-03-31 01:45:49,162.35.217.57,98.107.0.15,22505,25152,UDP,1043,Data,DNS,Enim at aspernatur illum. Saepe numquam eligen...,...,Blocked,Low,Samiha Joshi,Mozilla/5.0 (Windows; U; Windows NT 4.0) Apple...,Segment C,"Mahbubnagar, Himachal Pradesh",NaN,Log Data,Alert Data,Server
39998,2023-09-22 18:32:38,208.72.233.205,173.79.112.252,20013,2703,UDP,483,Data,FTP,Officiis dolorem sed harum provident earum dis...,...,Ignored,Low,Rasha Chauhan,Mozilla/5.0 (X11; Linux i686) AppleWebKit/536....,Segment B,"Rourkela, Arunachal Pradesh",137.76.130.8,Log Data,NaN,Server
39999,2023-10-10 11:59:52,14.102.21.108,109.198.45.7,50137,55575,ICMP,1175,Control,HTTP,Eligendi omnis voluptate nihil voluptatibus do...,...,Logged,Medium,Zaina Kumar,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like M...,Segment A,"Pudukkottai, West Bengal",112.169.115.139,Log Data,Alert Data,Firewall

In [53]:
df.isnull().sum()     #to get the actual number of null values

Timestamp                     0
Source IP Address             0
Destination IP Address        0
Source Port                   0
Destination Port              0
Protocol                      0
Packet Length                 0
Packet Type                   0
Traffic Type                  0
Payload Data                  0
Malware Indicators        20000
Anomaly Scores                0
Alerts/Warnings           20067
Attack Type                   0
Attack Signature              0
Action Taken                  0
Severity Level                0
User Information              0
Device Information            0
Network Segment               0
Geo-location Data             0
Proxy Information         19851
Firewall Logs             19961
IDS/IPS Alerts            20050
Log Source                    0
dtype: int64

In [54]:
df[['Malware Indicators','Alerts/Warnings']]

      Malware Indicators  Alerts/Warnings
0           IoC Detected              NaN
1           IoC Detected              NaN
2           IoC Detected  Alert Triggered
3                    NaN  Alert Triggered
4                    NaN  Alert Triggered
...                  ...              ...
39995       IoC Detected              NaN
39996       IoC Detected              NaN
39997       IoC Detected              NaN
39998       IoC Detected  Alert Triggered
39999                NaN  Alert Triggered

[40000 rows x 2 columns]

In [55]:
df.describe()    #accessing the statistical summary of the data set

        Source Port  Destination Port  Packet Length  Anomaly Scores
count  40000.000000      40000.000000   40000.000000    40000.000000
mean   32970.356450      33150.868650     781.452725       50.113473
std    18560.425604      18574.668842     416.044192       28.853598
min     1027.000000       1024.000000      64.000000        0.000000
25%    16850.750000      17094.750000     420.000000       25.150000
50%    32856.000000      33004.500000     782.000000       50.345000
75%    48928.250000      49287.000000    1143.000000       75.030000
max    65530.000000      65535.000000    1500.000000      100.000000

In [56]:
df.info()     #getting general information about the columns

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Timestamp               40000 non-null  str
 1   Source IP Address       40000 non-null  str
 2   Destination IP Address  40000 non-null  str
 3   Source Port             40000 non-null  int64
 4   Destination Port        40000 non-null  int64
 5   Protocol                40000 non-null  str
 6   Packet Length           40000 non-null  int64
 7   Packet Type             40000 non-null  str
 8   Traffic Type            40000 non-null  str
 9   Payload Data            40000 non-null  str
 10  Malware Indicators      20000 non-null  str
 11  Anomaly Scores          40000 non-null  float64
 12  Alerts/Warnings         19933 non-null  str
 13  Attack Type             40000 non-null  str
 14  Attack Signature        40000 non-null  str
 15  Action Taken            40000 non-null  str
 16  Severity Level          40000 non-null  str
 17  User Information        40000 non-null  str
 18  Device Information      40000 non-null  str
 19  Network Segment         40000 non-null  str
 20  Geo-location Data       40000 non-null  str
 21  Proxy Information       20149 non-null  str
 22  Firewall Logs           20039 non-null  str
 23  IDS/IPS Alerts          19950 non-null  str
 24  Log Source              40000 non-null  str
dtypes: float64(1), int64(3), str(21)
memory usage: 7.6 MB

In [57]:
df.columns

Index(['Timestamp', 'Source IP Address', 'Destination IP Address',
       'Source Port', 'Destination Port', 'Protocol', 'Packet Length',
       'Packet Type', 'Traffic Type', 'Payload Data', 'Malware Indicators',
       'Anomaly Scores', 'Alerts/Warnings', 'Attack Type', 'Attack Signature',
       'Action Taken', 'Severity Level', 'User Information',
       'Device Information', 'Network Segment', 'Geo-location Data',
       'Proxy Information', 'Firewall Logs', 'IDS/IPS Alerts', 'Log Source'],
      dtype='str')

In [58]:
df[['Malware Indicators','Alerts/Warnings','Firewall Logs','IDS/IPS Alerts','Proxy Information']].head(10)

,Malware Indicators,Alerts/Warnings,Firewall Logs,IDS/IPS Alerts,Proxy Information
0,IoC Detected,NaN,Log Data,NaN,150.9.97.135
1,IoC Detected,NaN,Log Data,NaN,NaN
2,IoC Detected,Alert Triggered,Log Data,Alert Data,114.133.48.179
3,NaN,Alert Triggered,NaN,Alert Data,NaN
4,NaN,Alert Triggered,NaN,Alert Data,149.6.110.119
5,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,Log Data,NaN,NaN
7,IoC Detected,Alert Triggered,Log Data,Alert Data,192.31.159.5
8,IoC Detected,Alert Triggered,Log Data,Alert Data,NaN
9,NaN,Alert Triggered,NaN,NaN,87.128.245.244

In [59]:
# standardizing and encode null detection flags as explicit yes or no 

flag_cols = ['Malware Indicators','Alerts/Warnings','Firewall Logs','IDS/IPS Alerts','Proxy Information']
for col in flag_cols:
    df[col]=df[col].notna().map({True:'Yes',False:'No'})

df['proxy_used'] =  df['Proxy Information'].notna().map({True:'Yes',False:'No'})

In [60]:
df

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Severity Level,User Information,Device Information,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,proxy_used
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Low,Reyansh Dugal,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment A,"Jamshedpur, Sikkim",Yes,Yes,No,Server,Yes
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Low,Sumer Rana,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment B,"Bilaspur, Nagaland",No,Yes,No,Firewall,Yes
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Low,Himmat Karpe,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Segment C,"Bokaro, Rajasthan",Yes,Yes,Yes,Firewall,Yes
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Medium,Fateh Kibe,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...,Segment B,"Jaunpur, Rajasthan",No,No,Yes,Firewall,Yes
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Low,Dhanush Chad,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Segment C,"Anantapur, Tripura",Yes,No,Yes,Firewall,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-05-26 14:08:42,26.36.109.26,121.100.75.240,31005,6764,UDP,1428,Control,HTTP,Quibusdam ullam consequatur consequuntur accus...,...,Medium,Adira Madan,Mozilla/5.0 (iPad; CPU iPad OS 14_2_1 like Mac...,Segment A,"Nashik, Manipur",No,Yes,Yes,Firewall,Yes
39996,2023-03-27 00:38:27,17.21.163.81,196.108.134.78,2553,28091,UDP,1184,Control,HTTP,Quaerat neque esse. Animi expedita natus commo...,...,High,Rati Dara,Mozilla/5.0 (Windows; U; Windows 98; Win 9x 4....,Segment C,"Vadodara, Mizoram",Yes,Yes,No,Firewall,Yes
39997,2022-03-31 01:45:49,162.35.217.57,98.107.0.15,22505,25152,UDP,1043,Data,DNS,Enim at aspernatur illum. Saepe numquam eligen...,...,Low,Samiha Joshi,Mozilla/5.0 (Windows; U; Windows NT 4.0) Apple...,Segment C,"Mahbubnagar, Himachal Pradesh",No,Yes,Yes,Server,Yes
39998,2023-09-22 18:32:38,208.72.233.205,173.79.112.252,20013,2703,UDP,483,Data,FTP,Officiis dolorem sed harum provident earum dis...,...,Low,Rasha Chauhan,Mozilla/5.0 (X11; Linux i686) AppleWebKit/536....,Segment B,"Rourkela, Arunachal Pradesh",Yes,Yes,No,Server,Yes
39999,2023-10-10 11:59:52,14.102.21.108,109.198.45.7,50137,55575,ICMP,1175,Control,HTTP,Eligendi omnis voluptate nihil voluptatibus do...,...,Medium,Zaina Kumar,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like M...,Segment A,"Pudukkottai, West Bengal",Yes,Yes,Yes,Firewall,Yes

In [61]:
df[['Malware Indicators','Alerts/Warnings','Firewall Logs','IDS/IPS Alerts','Proxy Information']].head(10)

,Malware Indicators,Alerts/Warnings,Firewall Logs,IDS/IPS Alerts,Proxy Information
0,Yes,No,Yes,No,Yes
1,Yes,No,Yes,No,No
2,Yes,Yes,Yes,Yes,Yes
3,No,Yes,No,Yes,No
4,No,Yes,No,Yes,Yes
5,No,No,No,No,No
6,No,No,Yes,No,No
7,Yes,Yes,Yes,Yes,Yes
8,Yes,Yes,Yes,Yes,No
9,No,Yes,No,No,Yes

In [62]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])    #converting the data type of the timestamp to datetime form string

In [ ]:
# parsing the timestamp data into seperate hour,date,day of week,year month for further timer analysis

In [63]:
df['date'] = df['Timestamp'].dt.date

In [64]:
df['date'] = pd.to_datetime(df['date'])

In [65]:
df['hour'] = df['Timestamp'].dt.hour

In [68]:
df['day_of_week'] = df['Timestamp'].dt.day_name()
df['year_month'] = df['Timestamp'].dt.to_period('M')

In [69]:
df['day_of_week'] = df['day_of_week'].astype('string')

In [70]:
df['year_month']

0        2023-05
1        2020-08
2        2022-11
3        2023-07
4        2023-07
          ...
39995    2023-05
39996    2023-03
39997    2022-03
39998    2023-09
39999    2023-10
Name: year_month, Length: 40000, dtype: period[M]

In [72]:
df['hour'] = df['hour'].astype(int)

In [73]:
df.columns

Index(['Timestamp', 'Source IP Address', 'Destination IP Address',
       'Source Port', 'Destination Port', 'Protocol', 'Packet Length',
       'Packet Type', 'Traffic Type', 'Payload Data', 'Malware Indicators',
       'Anomaly Scores', 'Alerts/Warnings', 'Attack Type', 'Attack Signature',
       'Action Taken', 'Severity Level', 'User Information',
       'Device Information', 'Network Segment', 'Geo-location Data',
       'Proxy Information', 'Firewall Logs', 'IDS/IPS Alerts', 'Log Source',
       'proxy_used', 'date', 'hour', 'day_of_week', 'year_month'],
      dtype='str')

In [74]:
df[['Source Port', 'Destination Port']]

       Source Port  Destination Port
0            31225             17616
1            17245             48166
2            16811             53600
3            20018             32534
4             6131             26646
...            ...               ...
39995        31005              6764
39996         2553             28091
39997        22505             25152
39998        20013              2703
39999        50137             55575

[40000 rows x 2 columns]

In [75]:
# validating the source destination ports and flag well know ports (0-1023) vs registered/dynamic ports

df['source_port_category'] = np.where(
    df['Source Port']<=1023,
    'Well-Known',
     'Registered/Dynamic' 
)
df['destination_port_category'] = np.where(
    df['Destination Port']<=1023,
    'Well-Known',
     'Registered/Dynamic' 
)

In [76]:
df

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Firewall Logs,IDS/IPS Alerts,Log Source,proxy_used,date,hour,day_of_week,year_month,source_port_category,destination_port_category
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Yes,No,Server,Yes,2023-05-30,6,Tuesday,2023-05,Registered/Dynamic,Registered/Dynamic
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Yes,No,Firewall,Yes,2020-08-26,7,Wednesday,2020-08,Registered/Dynamic,Registered/Dynamic
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Yes,Yes,Firewall,Yes,2022-11-13,8,Sunday,2022-11,Registered/Dynamic,Registered/Dynamic
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,No,Yes,Firewall,Yes,2023-07-02,10,Sunday,2023-07,Registered/Dynamic,Registered/Dynamic
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,No,Yes,Firewall,Yes,2023-07-16,13,Sunday,2023-07,Registered/Dynamic,Registered/Dynamic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,2023-05-26 14:08:42,26.36.109.26,121.100.75.240,31005,6764,UDP,1428,Control,HTTP,Quibusdam ullam consequatur consequuntur accus...,...,Yes,Yes,Firewall,Yes,2023-05-26,14,Friday,2023-05,Registered/Dynamic,Registered/Dynamic
39996,2023-03-27 00:38:27,17.21.163.81,196.108.134.78,2553,28091,UDP,1184,Control,HTTP,Quaerat neque esse. Animi expedita natus commo...,...,Yes,No,Firewall,Yes,2023-03-27,0,Monday,2023-03,Registered/Dynamic,Registered/Dynamic
39997,2022-03-31 01:45:49,162.35.217.57,98.107.0.15,22505,25152,UDP,1043,Data,DNS,Enim at aspernatur illum. Saepe numquam eligen...,...,Yes,Yes,Server,Yes,2022-03-31,1,Thursday,2022-03,Registered/Dynamic,Registered/Dynamic
39998,2023-09-22 18:32:38,208.72.233.205,173.79.112.252,20013,2703,UDP,483,Data,FTP,Officiis dolorem sed harum provident earum dis...,...,Yes,No,Server,Yes,2023-09-22,18,Friday,2023-09,Registered/Dynamic,Registered/Dynamic
39999,2023-10-10 11:59:52,14.102.21.108,109.198.45.7,50137,55575,ICMP,1175,Control,HTTP,Eligendi omnis voluptate nihil voluptatibus do...,...,Yes,Yes,Firewall,Yes,2023-10-10,11,Tuesday,2023-10,Registered/Dynamic,Registered/Dynamic

In [4]:
# making a detection coverage score
flag_cols = ['Malware Indicators','Firewall Logs','IDS/IPS Alerts','Alerts/Warnings']
df['detection coverage score'] = (df[flag_cols]=='Yes').sum(axis=1)

In [78]:
df['detection coverage score']

0        2
1        2
2        4
3        2
4        2
        ..
39995    3
39996    2
39997    3
39998    3
39999    3
Name: detection coverage score, Length: 40000, dtype: int64

In [79]:
df[['Action Taken','Severity Level']]

      Action Taken Severity Level
0           Logged            Low
1          Blocked            Low
2          Ignored            Low
3          Blocked         Medium
4          Blocked            Low
...            ...            ...
39995       Logged         Medium
39996       Logged           High
39997      Blocked            Low
39998      Ignored            Low
39999       Logged         Medium

[40000 rows x 2 columns]

In [80]:
# creating a response alignment flag
df['Response Alignment'] = np.where(
                           (df['Action Taken']!='Blocked') & (df['Severity Level']=='High'),
                           1,
                           0)

In [81]:
# now comes the part of splitting the gepo location daa into different city region
df['Geo-location Data'].head(10)

0          Jamshedpur, Sikkim
1          Bilaspur, Nagaland
2           Bokaro, Rajasthan
3          Jaunpur, Rajasthan
4          Anantapur, Tripura
5       Aurangabad, Meghalaya
6              Eluru, Manipur
7    Phagwara, Andhra Pradesh
8             Ambala, Tripura
9             Rampur, Mizoram
Name: Geo-location Data, dtype: str

In [82]:
df['City'] = df['Geo-location Data'].str.split(',').str[0]

In [83]:
df['City']

0         Jamshedpur
1           Bilaspur
2             Bokaro
3            Jaunpur
4          Anantapur
            ...
39995         Nashik
39996       Vadodara
39997    Mahbubnagar
39998       Rourkela
39999    Pudukkottai
Name: City, Length: 40000, dtype: object

In [5]:
df['State'] = df['Geo-location Data'].str.split(',').str[1].str.strip()

In [6]:
df[['City','State']]

              City              State
0       Jamshedpur             Sikkim
1         Bilaspur           Nagaland
2           Bokaro          Rajasthan
3          Jaunpur          Rajasthan
4        Anantapur            Tripura
...            ...                ...
39995       Nashik            Manipur
39996     Vadodara            Mizoram
39997  Mahbubnagar   Himachal Pradesh
39998     Rourkela  Arunachal Pradesh
39999  Pudukkottai        West Bengal

[40000 rows x 2 columns]

In [3]:
# converting the cleaned dataset into csv format
df.to_csv('cleaned_cybersecurity_attacks.csv',index=False)

In [88]:
print(df.columns.tolist())
print(df.shape)

['Timestamp', 'Source IP Address', 'Destination IP Address', 'Source Port', 'Destination Port', 'Protocol', 'Packet Length', 'Packet Type', 'Traffic Type', 'Payload Data', 'Malware Indicators', 'Anomaly Scores', 'Alerts/Warnings', 'Attack Type', 'Attack Signature', 'Action Taken', 'Severity Level', 'User Information', 'Device Information', 'Network Segment', 'Geo-location Data', 'Proxy Information', 'Firewall Logs', 'IDS/IPS Alerts', 'Log Source', 'proxy_used', 'date', 'hour', 'day_of_week', 'year_month', 'source_port_category', 'destination_port_category', 'detection coverage score', 'Response Alignment', 'City', 'State']
(40000, 36)

In [7]:


df = pd.read_csv('cleaned_cybersecurity_attacks.csv')

print(df.iloc[0])

Unnamed: 0                                                                   0
Timestamp                                                  2023-05-30 06:33:58
Source IP Address                                                103.216.15.12
Destination IP Address                                            84.9.164.252
Source Port                                                              31225
Destination Port                                                         17616
Protocol                                                                  ICMP
Packet Length                                                              503
Packet Type                                                               Data
Traffic Type                                                              HTTP
Payload Data                 Qui natus odio asperiores nam. Optio nobis ius...
Malware Indicators                                                         Yes
Anomaly Scores                                                           28.67
Alerts/Warnings                                                             No
Attack Type                                                            Malware
Attack Signature                                               Known Pattern B
Action Taken                                                            Logged
Severity Level                                                             Low
User Information                                                 Reyansh Dugal
Device Information           Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...
Network Segment                                                      Segment A
Geo-location Data                                           Jamshedpur, Sikkim
Proxy Information                                                          Yes
Firewall Logs                                                              Yes
IDS/IPS Alerts                                                              No
Log Source                                                              Server
proxy_used                                                                 Yes
date                                                                2023-05-30
hour                                                                         6
day_of_week                                                            Tuesday
year_month                                                             2023-05
source_port_category                                        Registered/Dynamic
destination_port_category                                   Registered/Dynamic
detection coverage score                                                     2
Response Alignment                                                           0
City                                                                Jamshedpur
State                                                                   Sikkim
Name: 0, dtype: object